export const associations = {
  'mobs': ['мобы', 'существа', 'монстры', 'юниты', 'статы мобов', 'характеристики существ', 'mobs', 'units', 'monsters', 'creatures', 'enemies'],
  'comparator': ['сравнить существ', 'сопоставить существ', 'компаратор', 'comparing', 'matching', 'stronger unit'],
  'damagecalc': ['калькулятор урона', 'расчитать урон', 'calculate damage', 'how much damage'],
  'artifacts': ['артефакты', 'арты', 'лут', 'шмот', 'оружие', 'броня', 'кольца', 'амулеты', 'artefacts', 'relics', 'weapon', 'armor', 'necklects', 'items', 'loot', 'rings', 'talismans', 'books', 'chest', 'head', 'hands', 'offhand', 'shield', 'gauntlets', 'glowes', 'boots', 'cloak', 'sword', 'orbs', 'amulet'],
  'heroes': ['герои', 'чары', 'чемпионы', 'персонажи', 'персы', 'стартовая армия', 'биография', 'heroes', 'champions', 'characters', 'biography', 'starting army', 'starting stats', 'heroes specialty'],
  'spells': ['заклинания', 'спеллы', 'магия', 'вода', 'огонь', 'земля', 'воздух', 'spells', 'magic', 'abiliteis', 'enchantment', 'sorcery', 'fire', 'water', 'earth', 'air', 'mana cost', 'spell sost', 'spell affinity'],
  'objects': ['игровые объекты', 'объекты', 'сокровищницы', 'двелл', 'карта приключений', 'жилища', 'шахты', 'порталы', 'dwellings', 'objects', 'treasury', 'vaults', 'adventure map', 'mines', 'portals', 'outposts'],
  'maps': ['карты', 'мапы', 'пользовательские карты', 'кастомные карты', 'скачать карты', 'custom maps', 'download maps'],
  'towns': ['города', 'замки', 'постройки', 'цепочка построек', 'карта загадки', 'towns', 'castles', 'town buildings', 'building order', 'grail maps', 'town units', 'town heroes', 'town music theme', 'town description'],
  'about': ['о проекте', 'о сайте hommbase', 'наша миссия', 'about us', 'about project', 'hommbase', 'about hommbase'],
  'community': ['софт', 'программы', 'утилиты', 'патчи', 'проги', 'дополнения', 'hota скачать', 'герои 3 скачать', 'игровые сообщества', 'сообщества героев 3', 'сайты по героям 3', 'стримы', 'форумы', 'software', 'programs', 'patches', 'updates', 'download hota', 'community', 'heroes 3 youtube', 'heroes 3 twitch', 'heroes 3 forums'],
  'tests': ['тесты', 'викторина', 'челлендж', 'quiz', 'game knowledge tests'],
  'records': ['результаты тестов', 'таблица рекордов', 'лучшие результаты', 'table of records', 'best results'],
  'mechanics': ['механики игры', 'секреты', 'хитрости', 'информация по игре', 'game mechanics', 'hidden mechanics'],
  'mechanics?alias=editor': ['редактор карт', 'гайд по редактору', 'создание карт', 'map editor guide', 'custom maps creation', 'map editor tutorials'],
  'mechanics?alias=editor_control': ['кнопки редактора', 'панели редактора', 'map editor panel'],
  'mechanics?alias=editor_terrain': ['работа с почвой и рельефом', 'ground editing', 'soil editing', 'land editing'],
  'mechanics?alias=editor_placement': ['размещение объектов', 'редактирование объектов', 'object placement', 'object editing'],
  'mechanics?alias=editor_settings': ['настройки карты', 'спецификации карты', 'map settings'],
  'mechanics?alias=editor_ideas': ['идеи для карт', 'приемы создания карт', 'custom maps patterns', 'custom maps examples'],
  'mechanics?alias=damage_basic': ['урон', 'атака', 'защита', 'рассчет урона', 'offence', 'deffence', 'attack', 'protection', 'resist', 'damage calculation'],
  'mechanics?alias=damage_mod': ['модификаторы урона', 'damage modifier'],
  'mechanics?alias=damage_reduce': ['отрицательные параметры', 'характеристики ниже нуля', 'negative characteristics'],
  'mechanics?alias=luck_morale': ['удача', 'боевой дух', 'мораль', 'дополнительный ход', 'пропуск хода', 'luck', 'morale'],
  'mechanics?alias=shooting_count': ['стрельба', 'archery'],
  'mechanics?alias=shooting_penalty': ['штрафы стрельбы', 'shooting penalty'],
  'mechanics?alias=blocking': ['блокирование', 'shooters blocking'],
  'mechanics?alias=unit_health': ['здоровье существ', 'хп', 'хиты', 'hp', 'health points', 'resilience'],
  'mechanics?alias=unit_speed': ['скорость существ', 'передвижение', 'очки передвижения', 'штрафы местности', 'unit movement', 'ground penalty'],
  'mechanics?alias=movement': ['запас хода', 'мп', 'дороги', 'movement points', 'roads'],
  'mechanics?alias=movement_map': ['посещение объектов', 'разгон', 'разведка', 'objects attending', 'movement boost', 'scouting'],
  'mechanics?alias=ai': ['ии', 'компьютерный игрок', 'искуственный интеллект', 'уровень сложности', 'сложность', 'поведение ии', 'computer ai', 'game difficulty', 'ai behaviour'],
  'mechanics?alias=attack_decision': ['агрессия', 'ai aggression'],
  'mechanics?alias=spell_value': ['выбор заклинаний ии', 'ценность заклинаний', 'ai spell choice', 'ai spell value'],
  'mechanics?alias=ai_battle': ['движение ии в бою', 'ai movement'],
  'mechanics?alias=battle_basics': ['основы сражения', 'бой', 'битва', 'battle tutorial', 'fight tutorial'],
  'mechanics?alias=standard_battlefield': ['поле боя', 'группировка', 'сосредоточение', 'строй', 'battlefield', 'formation'],
  'mechanics?alias=obstacles': ['препятствия в бою', 'закрытые гексы', 'изолированные гексы', 'генерация поля боя', 'battlefield objects', 'battlefield generation'],
  'mechanics?alias=unit_separation': ['разделение отрядов', 'army splitting'],
  'mechanics?alias=hero_battle': ['сбежать', 'побег', 'откупиться', 'капитуляция', 'сдаться', 'surrender', 'buyout'],
  'mechanics?alias=unit_battle': ['подождать', 'защититься', 'укрепить позицию', 'to wait', 'to defend'],
  'mechanics?alias=treasuries': ['захват сокровищниц', 'пробитие охраны', 'treasure battle'],
  'mechanics?alias=battle_rounds': ['порядок ходов', 'перемещение в бою', 'раунды битвы', 'turn order on battlefield', 'battle rounds'],
  'mechanics?alias=unit_growth': ['прирост существ', 'базовый прирост', 'население', 'unit population growth'],
  'mechanics?alias=weeks_months': ['недели существ', 'месяцы существ', 'чума', 'недели чумы', 'plague week', 'unit week', 'unit month'],
  'mechanics?alias=unit_status': ['статус существ', 'нежить', 'големы', 'живые существа', 'горгульи', 'элементали', 'unit status', 'undead', 'golems', 'alive', 'gargoyle', 'elementals'],
  'mechanics?alias=native_land': ['почва', 'родная земля', 'местность', 'homeland', 'homeground'],
  'mechanics?alias=counterstrike': ['контратака', 'контрудар', 'ответка', 'сдача', 'counterstrike', 'counterpunch'],
  'mechanics?alias=hatred': ['ненависть', 'заклятые враги', 'антагонисты', 'antagonism'],
  'mechanics?alias=spell_neutralize': ['нейтрализация заклинаний', 'сопротивление магии', 'magic neutralisation', 'magic resistance'],
  'mechanics?alias=spell_absorption': ['поглощение', 'резист', 'снижение урона', 'damage absorbtion'],
  'mechanics?alias=fire_breath': ['огненное дыхание', 'дыхание драконов', 'прожиг', 'массовая атака', 'фэйк прожиг', 'разворот и атака', 'dragons breath', 'splash attack', 'fake splash attack'],
  'mechanics?alias=cavalry': ['способности существ', 'скиллы мобов', 'особенности существ', 'рут', 'заклинания существ', 'units abilites', 'root', 'blind'],
  'mechanics?alias=archangels': ['воскрешение', 'ressurection'],
  'mechanics?alias=poison': ['яд', 'старость', 'poison', 'senescence', 'ageing'],
  'mechanics?alias=blind': ['стан', 'паралич', 'окаменение', 'stun', 'petrification', 'paralyze'],
  'mechanics?alias=combat_vehicles': ['боевые машины', 'осадные машины', 'машины', 'siege machinery', 'siege engines'],
  'mechanics?alias=catapult': ['катапульта', 'catapult'],
  'mechanics?alias=ballist': ['баллиста', 'ballista'],
  'mechanics?alias=cannon': ['пушка', 'cannon'],
  'mechanics?alias=first_aid_tent': ['палатка', 'tent'],
  'mechanics?alias=ammo_cart': ['подвода с боеприпасами', 'тележка', 'ammunition cart'],
  'mechanics?alias=spell_adaptive': ['механика заклинаний', 'особенности заклинаний', 'spell mechanics', 'spell tips'],
  'mechanics?alias=fire_wall': ['стена огня', 'огненная стена', 'стенка', 'fire wall', 'wall of fire'],
  'mechanics?alias=berserk': ['берсерк', 'berserk'],
  'mechanics?alias=fire_shield': ['огненный щит', 'щит огня', 'щит ифритов', 'fire shield', 'efreet shield'],
  'mechanics?alias=teleport': ['телепорт', 'блинк', 'teleport'],
  'mechanics?alias=clone': ['клон', 'двойник', 'clone', 'kagebunshin-no-jutsu'],
  'mechanics?alias=disguise': ['маскировка', 'disguise'],
  'mechanics?alias=hypnotize': ['гипноз', 'контроль', 'hypnosis'],
  'mechanics?alias=chain_lightning': ['цепная молния', 'чайник', 'chain lightning'],
  'mechanics?alias=fly': ['полет', 'флай', 'fly'],
  'mechanics?alias=anti_magic': ['антимагия', 'antimagic'],
  'mechanics?alias=force_field': ['силовое поле', 'форс филд', 'force field'],
  'mechanics?alias=spell_ground': ['заклинания на землю', 'устанавливаемые заклинания', 'ground based spells'],
  'mechanics?alias=hero_spell_spec': ['специализации героев', 'специализация по заклинаниям', 'heroes specialty', 'spell specialty'],
  'mechanics?alias=primary': ['первичные навыки', 'статы героев', 'основные параметры', 'мана', 'primary characteristics', 'primary stats', 'base characteristics', 'base stats'],
  'mechanics?alias=secondary': ['вторичные навыки', 'умения героев', 'скиллы героев', 'secondary skills', 'hero skills', 'hero abilities'],
  'mechanics?alias=hero_classes': ['классы героев', 'heroes classification'],
  'mechanics?alias=grail_excavaition': ['грааль', 'раскопки грааля', 'grail', 'serching and digging the grail'],
  'mechanics?alias=grail_temple': ['храм грааля', 'grail temple', 'grail building'],
  'mechanics?alias=fortification': ['фортификации', 'осада города', 'штурм города', 'городские укрепления', 'оборонные сооружения', 'town fortification', 'town siege'],
  'mechanics?alias=town_walls': ['стены города', 'ворота', 'town walls', 'town gates'],
  'mechanics?alias=shooting_towers': ['стрелковые башни', 'town towers'],
  'mechanics?alias=moat': ['ров', 'мины', 'town mines', 'ditch', 'trench'],
  'mechanics?alias=start_bonuses': ['стартовые бонусы', 'выбор бонуса', 'start bonus choise'],
  'mechanics?alias=orb_vulnerability': ['сфера уязвимости', 'уязвимость к заклинаниям', 'orb of vulnerability', 'spell vulnerability'],
  'mechanics?alias=cheats': ['читы', 'коды', 'cheat codes'],
  'mechanics?alias=common_keys': ['горячие клавиши', 'комбинации клавиш', 'быстрые действия', 'hot keys', 'quick action keys'],
  'mechanics?alias=gamemode_arena': ['режим арена', 'arena maps'],
  'auth/profile': ['профиль пользователя', 'личный кабинет', 'сменить аватар', 'my profile', 'change profile picture']
}
